[package]
name = "assembler_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rev_slice = "0.1.5"
hex = "0.3.1"
to-binary = "0.4.0"

[env]
RUST_BACKTRACE=1